### ISSUE TITLE
How can I costumize the appearance of map_plot output?

### ISSUE THREAD

**Issue by annawenzel** [SoerenPannier/emdi#13]
I am currently using the emdi package for a seminar paper. Unfortunately, I am unable to find the following information in the documentation: how can I label the colorbar, change the line colors, add a title to the map and get rid of the grid in the background?
Could you tell me where to find detailed information or forward an explicit example to me?
I used the following command to create the attached image:
```
map_plot(est_fh, MSE = T, CV =F, map_obj = my_spdf, 
         indicator = "FH", map_dom_id = "ID", map_tab = map_tab, return_data = T,scale_points = c(0,1)) 
```

Thanks in advance!
Anna
![Rplot](https://user-images.githubusercontent.com/80355515/110522623-60006d80-8111-11eb-8516-3f0cbb3929a6.png)

**Comment by SoerenPannier** [comment]
Hi Anna,

map_plot sadly is not super customizable yet, but you can use the use the `return_data ` argument to get the merged fortified `data.frame` containing the indicator of concern and the polygon data. The code below should be helpful:

```

library(emdi)
library(ggplot2)

data("eusilcA_pop")
data("eusilcA_smp")

# Generate emdi object with additional indicators; here via function ebp()
emdi_model <- ebp(fixed = eqIncome ~ gender + eqsize + cash + 
                    self_empl + unempl_ben + age_ben + surv_ben + sick_ben + dis_ben + rent + 
                    fam_allow + house_allow + cap_inv + tax_adj, pop_data = eusilcA_pop,
                  pop_domains = "district", smp_data = eusilcA_smp, smp_domains = "district",
                  threshold = 11064.82, transformation = "box.cox", L= 5, MSE = FALSE, B = 50)

# Load shape file
load_shapeaustria()

indicator_to_plot <- "Mean"

# Create map plot for mean indicator - point and MSE estimates but no CV
map_data <-  map_plot(object = emdi_model, MSE = FALSE, CV = FALSE, 
         map_obj = shape_austria_dis, indicator = c(indicator_to_plot), 
         map_dom_id = "PB", return_data = TRUE)

theme_set(theme_void())
ggplot(map_data, aes(long, lat, group = group, 
                fill = map_data[indicator_to_plot][, 1])) + geom_polygon(color = "azure3") + 
  coord_equal() + labs(x = "", y = "", fill = indicator_to_plot) +
  ggtitle("Title") + 
  scale_fill_gradient(name = "Legend Name")

```

However, we should return a list of the created plots as default, so they can be customized more easily. I'll add a task for this.

Best 

Sören
