### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by akreutzmann** [SoerenPannier/emdi#2]
The summary did show 0 sample sizes for the minimum, mean etc. 
It should show the lowest sample size except the 0s. 

I added
smp_domains_vec <- droplevels(smp_domains_vec)

in framework_ebp

in 

  # Order of domains
  pop_data <- pop_data[order(pop_data[[pop_domains]]),]
  pop_data[[pop_domains]] <- factor(pop_data[[pop_domains]], levels = unique(pop_data[[pop_domains]]))
  pop_domains_vec <- pop_data[[pop_domains]]

  smp_data <- smp_data[order(smp_data[[smp_domains]]),]
  smp_data[[smp_domains]] <- factor(smp_data[[smp_domains]], levels = unique(pop_data[[pop_domains]]))
  smp_domains_vec <- smp_data[[smp_domains]]
  smp_domains_vec <- droplevels(smp_domains_vec)

We should check if this solves the problem

**Comment by SoerenPannier** [comment]
It did 👍
